# Cuaderno Jupyter

<p>Jupyter es una aplicación web de código abierto que ha sido desarrollada utilizando lenguaje HTML. Con esto se ha conseguido que los usuarios podamos crear, compartir y editar documentos en los que se puede ejecutar código Python en nuestro navegador. También podremos hacer anotaciones, insertar ecuaciones, visualizar resultados y documentar funcionalidades.</p>
<p>Si con anterioridad hemos instalado Anaconda Distribution ya tendremos instalado Jupyter Notebook. Por lo que podremos ejecutarlo desde la terminal (Ctrl+Alt+T) escribiendo:</p>
<br>
<code style="margin-left:23px">jupyter-notebook</code>
<p>En caso de que no querer instalar Anaconda Distribution tendremos la opción de poder instalar Jupyter Notebook utilizando pip de Python. Para ello, solo tendremos que abrir una terminal (Ctrl+Alt+T) y ejecutar el siguiente comando:</p>
<br>
<code style="margin-left:23px">pip install notebook</code>
<p>Una vez terminada la instalación, ya podremos lanzar el programa utilizando el siguiente comando en la misma terminal:</p>
<br>
<code style="margin-left:23px">jupyter-notebook</code>
<p>Sólo queda importar el archivo con extensión ".ipynb" y podra ser modificado y ejecutado el código que contiene. La forma más rápida y cómoda, y que evita errores, es seleccionar en el menú superior "Kernel" la opción "Restart & Run All"</p>

# Practica 01 - Primalidad

In [1]:
import numpy as np
import time
from random import randint

def potenciaModular(base, exponente, modulo):
    aux = 1
    while (exponente > 0):
        if (exponente%2 == 1):
            aux = (aux*base)%modulo
        exponente = exponente//2
        base = (base*base)%modulo
    return aux

## Ejercicio 01
##### Dado un número impar n tenemos que decidir si n es primo o no (con un pequeño margen de error). Para esto, usaremos el test de Miller-Rabin, y tenemos que decidir cuántos testigos elegimos para que la probabilidad de error sea pequeña. Si se quiere, antes de pasar el test de Miller-Rabin podemos probar a dividir el número n por los primeros números primos. Si en algún caso la división es exacta, ya tendríamos que el número no es primo.

In [2]:
def crearTabla(base, modulo):
    aux = int(modulo-1)
    print("\na **", aux, " mod ", modulo, "= \t", potenciaModular(base, aux, modulo))
    while (aux%2 == 0):
        aux = int(aux/2)
        print("a **", aux, " mod ", modulo, " = \t", potenciaModular(base, aux, modulo))
    if(aux != 1):
        print("a ** 1 = \t", base)

def MRvalidate(base, modulo, b):
    result = False
    if (base == 1 or base == modulo-1):
        result = True
    else:
        for i in range(1, b):
            base = potenciaModular(base, 2, modulo)
            aux = base
            if (base == modulo-1):
                result = True
                break
            elif (base == 1):
                result = False
                break
    return result
    
def testMillerRabin(p, testigos, function = None):
    b = 1
    s = 0
    if (p%2 != 0 and p >= 5):
        aux = (p-1)/2
        while (aux%2 == 0):
            aux /= 2
            b += 1
        s = int(aux)
        for a in testigos:
            if (function != None):
                function(a, p)
            a_1 = potenciaModular(a, s, p)
            result = MRvalidate(a_1, p, b)
            if result == 0:
                print("Para el testigo a = ", a, ", p = ", p, "No es primo")
            elif result == 1:
                print("Para el testigo a = ", a, ", p = ", p, "Es probable primo")
    else:
        print("\nValor de P no valido")

In [3]:
p = 31307 # Es Primo
n_testigos = 10
testigos = np.random.randint(2, p-2, size = n_testigos).tolist()
testMillerRabin(p, testigos)

Para el testigo a =  20655 , p =  31307 Es probable primo
Para el testigo a =  25939 , p =  31307 Es probable primo
Para el testigo a =  678 , p =  31307 Es probable primo
Para el testigo a =  26633 , p =  31307 Es probable primo
Para el testigo a =  18948 , p =  31307 Es probable primo
Para el testigo a =  1809 , p =  31307 Es probable primo
Para el testigo a =  31304 , p =  31307 Es probable primo
Para el testigo a =  13551 , p =  31307 Es probable primo
Para el testigo a =  3223 , p =  31307 Es probable primo
Para el testigo a =  2439 , p =  31307 Es probable primo


<p>El número utilizado, 31307, es primo. El test de Miller-Rabin arroja que es un probable primo. Se han utilizado para ello 10 testigos aleatorios generados con Numpy.</p>

In [4]:
p = 52151 # No Es Primo
n_testigos = 10
testigos = np.random.randint(2, p-2, size = n_testigos).tolist()
testMillerRabin(p, testigos)

Para el testigo a =  17613 , p =  52151 No es primo
Para el testigo a =  45447 , p =  52151 No es primo
Para el testigo a =  18871 , p =  52151 No es primo
Para el testigo a =  48442 , p =  52151 No es primo
Para el testigo a =  23968 , p =  52151 No es primo
Para el testigo a =  26249 , p =  52151 No es primo
Para el testigo a =  17414 , p =  52151 No es primo
Para el testigo a =  35432 , p =  52151 No es primo
Para el testigo a =  1221 , p =  52151 No es primo
Para el testigo a =  33447 , p =  52151 No es primo


<p>El número utilizado, 52151, no es primo. El test de Miller-Rabin arroja que no es un número primo. Se han utilizado para ello 10 testigos aleatorios generados con Numpy.</p>

## Ejercicio 02.
#### Tenemos que implementar una versión del test de Miller-Rabin que nos permita hacer pruebas. Hay que poder decidir para un número n compuesto e impar, si un número a es un falso testigo o no lo es.

In [5]:
p = 60373 # Es Primo
n_testigos = 10
testigos = np.random.randint(2, p-2, size = n_testigos).tolist()
testMillerRabin(p, testigos, crearTabla)


a ** 60372  mod  60373 = 	 1
a ** 30186  mod  60373  = 	 1
a ** 15093  mod  60373  = 	 1
a ** 1 = 	 51697
Para el testigo a =  51697 , p =  60373 Es probable primo

a ** 60372  mod  60373 = 	 1
a ** 30186  mod  60373  = 	 60372
a ** 15093  mod  60373  = 	 59596
a ** 1 = 	 23247
Para el testigo a =  23247 , p =  60373 Es probable primo

a ** 60372  mod  60373 = 	 1
a ** 30186  mod  60373  = 	 1
a ** 15093  mod  60373  = 	 60372
a ** 1 = 	 20872
Para el testigo a =  20872 , p =  60373 Es probable primo

a ** 60372  mod  60373 = 	 1
a ** 30186  mod  60373  = 	 1
a ** 15093  mod  60373  = 	 1
a ** 1 = 	 16274
Para el testigo a =  16274 , p =  60373 Es probable primo

a ** 60372  mod  60373 = 	 1
a ** 30186  mod  60373  = 	 60372
a ** 15093  mod  60373  = 	 777
a ** 1 = 	 35337
Para el testigo a =  35337 , p =  60373 Es probable primo

a ** 60372  mod  60373 = 	 1
a ** 30186  mod  60373  = 	 1
a ** 15093  mod  60373  = 	 1
a ** 1 = 	 27264
Para el testigo a =  27264 , p =  60373 Es probabl

In [6]:
p = 60371 # No Es Primo
n_testigos = 10
testigos = np.random.randint(2, p-2, size = n_testigos).tolist()
testMillerRabin(p, testigos, crearTabla)


a ** 60370  mod  60371 = 	 18669
a ** 30185  mod  60371  = 	 34484
a ** 1 = 	 1182
Para el testigo a =  1182 , p =  60371 No es primo

a ** 60370  mod  60371 = 	 39309
a ** 30185  mod  60371  = 	 38126
a ** 1 = 	 6137
Para el testigo a =  6137 , p =  60371 No es primo

a ** 60370  mod  60371 = 	 28662
a ** 30185  mod  60371  = 	 50392
a ** 1 = 	 54188
Para el testigo a =  54188 , p =  60371 No es primo

a ** 60370  mod  60371 = 	 54189
a ** 30185  mod  60371  = 	 29552
a ** 1 = 	 53191
Para el testigo a =  53191 , p =  60371 No es primo

a ** 60370  mod  60371 = 	 7135
a ** 30185  mod  60371  = 	 20103
a ** 1 = 	 14614
Para el testigo a =  14614 , p =  60371 No es primo

a ** 60370  mod  60371 = 	 53033
a ** 30185  mod  60371  = 	 53091
a ** 1 = 	 40812
Para el testigo a =  40812 , p =  60371 No es primo

a ** 60370  mod  60371 = 	 30079
a ** 30185  mod  60371  = 	 24549
a ** 1 = 	 20178
Para el testigo a =  20178 , p =  60371 No es primo

a ** 60370  mod  60371 = 	 57162
a ** 30185  

<p>Se ha incluido una función que muestra la tabla de cálculos para poder comprobar si son falsos testigos.</p>

## Ejericio 03.
#### Hay que hacer una función que, dado un número n, calcule el siguiente número primo (mejor dicho, el siguiente probable primo).

In [7]:
def posiblePrimo(p, testigos):
    b = 1
    s = 0
    state = 1
    if (p%2 != 0 and p >= 5):
        aux = (p-1)/2
        while (aux%2 == 0):
            aux /= 2
            b += 1
        s = int(aux)
        for a in testigos:
            a_1 = potenciaModular(a, s, p)
            result = MRvalidate(a_1, p, b)
            if result == 0:
                state = 0
                break
        return state
    else:
        return 0
        
def nextPrimo(m, n_testigos, fuerte = False):
    candidato = m
    if(candidato%2 == 0):
        candidato += 1
    else:
        candidato += 2
    testigos = np.random.randint(2, candidato-2, size = n_testigos).tolist()
    if(fuerte == False):
        while ((posiblePrimo(candidato, testigos)) == 0):
            candidato += 2
            testigos = np.random.randint(2, candidato-2, size = n_testigos).tolist()
        print("El siguiente primo probable es: ", candidato)
    else:
        estado = posiblePrimo(candidato, testigos)
        while True:
            if estado == 1:
                if posiblePrimo(int((candidato-1)/2), testigos) == 1:
                    break
            candidato += 2
            testigos = np.random.randint(2, candidato-2, size = n_testigos).tolist()
            estado = posiblePrimo(candidato, testigos)
        print("El siguiente primo fuerte probable es: ", candidato)

In [8]:
m = 77023 # El siguiente Primo es 77029
n_testigos = 10
nextPrimo(m, n_testigos)

El siguiente primo probable es:  77029


<p>Se ha modificado la función de manera que devuelve 0 si no es primo y 1 si es un posible primo. Al pasarle la variable fuerte en Falso accedemos a esta función que comprueba si un número es primo o no y va incrementando el candidato a primo hasta encontrar uno que sea posible primo, que es el que devuelve.</p>

## Ejercicio 04.
#### Hay que hacer una función que, dado un número n, calcule el siguiente número primo fuerte. Un número p es un primo fuerte si tanto él como $ \frac{p-1}{2} $ son números primos.

In [9]:
m = 94651
n_testigos = 10
state = True
nextPrimo(m, n_testigos, state)

El siguiente primo fuerte probable es:  94727


<p>Se ha utilizado la función modificada anteriormente. Al pasarle la variable fuerte en True accedemos a esta función que comprueba si un número es primo fuerte o no y va incrementando el candidato a primo hasta encontrar uno que sea posible primo fuerte, que es el que devuelve. Este caso difiere del anterior en la comprobacion de que ademas de posible primo, sea fuerte.</p>

## Ejercicio 05.
#### Dado un número n hay que calcular un número primo (fuerte) con n bits (es decir, un primo p tal que $ 2^{n-1} \leq p < 2^{n} $).

In [10]:
def nextPrimoBits(m, n_testigos):
    candidato = m
    lowValor = 2**(m-1)
    highValor = 2**m
    state = False
    if(lowValor == 0):
        candidato = lowValor+1
    else:
        candidato == lowValor
    testigos = np.random.randint(2, candidato-2, size = n_testigos).tolist()
    estado = posiblePrimo(candidato, testigos)
    while candidato < highValor:
        if estado == 1:
            if (lowValor <= candidato and candidato < highValor):
                if posiblePrimo(int((candidato-1)/2), testigos) == 1:
                    state = True
                    break
        candidato += 2
        testigos = np.random.randint(2, candidato-2, size = n_testigos).tolist()
        estado = posiblePrimo(candidato, testigos)
    if(state):
        print("El siguiente primo fuerte probable con bits n = ", m, " es ", candidato)
    else:
        print("No existe primo fuerte con los bits dados")

In [11]:
m = 11
n_testigos = 10
nextPrimoBits(m, n_testigos)

El siguiente primo fuerte probable con bits n =  11  es  1187


<p>Se ha utilizado la función modificada anteriormente. Se busca un posible primo fuerte comprobando los valores dentro del rango especificado. Si no se encontrara ninguno, devolvería dicho mensaje. En este caso, cuanto mayor es el número especificado, mayor es el rango y mas costoso resulta encontrar un posible primo fuerte.</p>

## Ejercicio 06.
#### Elegimos un número de la siguiente lista: 
#### 6601   8911   10585   15841   29341
#### Para el número elegido tenemos que encontrar todos los falsos testigos.

In [12]:
def testMillerRabinFalsos(p, testigos, function = None):
    b = 1
    s = 0
    falseResults = ''
    contador = 0
    if (p%2 != 0 and p >= 5):
        aux = (p-1)/2
        while (aux%2 == 0):
            aux /= 2
            b += 1
        s = int(aux)
        for a in testigos:
            if (function != None):
                function(a, p)
            a_1 = potenciaModular(a, s, p)
            result = MRvalidate(a_1, p, b)
            if result == 1:
                falseResults = falseResults + str(a) + ', '
                contador += 1
        if(len(falseResults) == 0):
            print("No se han obtenido falsos testigos")
        else:
            print(falseResults[0:len(falseResults)-2])
            print("\nEn total, se han obtenido ", contador, " falsos testigos de ", len(testigos))
    else:
        print("\nValor de P no valido")

In [13]:
p = 6601
n_testigos = p-5
aux = 2
testigos = np.array([aux])
for i in range(n_testigos):
    aux += 1
    testigos = np.append(testigos, [aux], axis = 0)
testMillerRabinFalsos(p, testigos)

16, 18, 40, 45, 66, 78, 100, 122, 141, 165, 195, 242, 250, 256, 286, 288, 303, 305, 318, 324, 327, 332, 338, 433, 474, 482, 508, 517, 523, 573, 605, 611, 619, 625, 640, 652, 715, 720, 739, 769, 795, 804, 810, 821, 824, 830, 843, 845, 877, 898, 927, 961, 983, 1002, 1056, 1082, 1091, 1108, 1111, 1117, 1132, 1147, 1166, 1185, 1188, 1193, 1199, 1205, 1248, 1270, 1289, 1313, 1369, 1378, 1404, 1417, 1451, 1453, 1466, 1513, 1527, 1576, 1581, 1600, 1630, 1644, 1671, 1682, 1691, 1721, 1738, 1753, 1762, 1767, 1773, 1779, 1788, 1800, 1868, 1887, 1931, 1952, 1964, 1972, 1993, 2008, 2010, 2025, 2027, 2054, 2060, 2075, 2101, 2109, 2131, 2174, 2196, 2204, 2218, 2245, 2256, 2259, 2312, 2347, 2396, 2483, 2491, 2505, 2526, 2538, 2543, 2567, 2584, 2601, 2614, 2634, 2640, 2661, 2705, 2729, 2770, 2813, 2830, 2869, 2888, 2907, 2915, 2927, 2936, 2948, 2962, 2970, 3057, 3079, 3091, 3117, 3120, 3139, 3156, 3175, 3188, 3202, 3249, 3298, 3303, 3352, 3399, 3413, 3426, 3445, 3462, 3481, 3484, 3510, 3522, 3544, 363

<p>Se ha modificado la función para mostrar todos los falsos testigos.</p>

## Ejercicio 07.
#### Elegimos dos números compuestos grandes (uno que sea producto de varios números primos pequeños y otro que sea producto de dos números primos grandes. Para elegir estos primos usaremos alguna de las funciones que hemos implementado en los aparatados 3, 4 ó 5). Para estos dos primos, elegiremos al azar doscientos testigos y veremos cuáles son falsos.

In [14]:
m = 100
n_testigos = 10
state = True
nextPrimo(m, n_testigos, state)
m = 200
nextPrimo(m, n_testigos, state)
m = 300
nextPrimo(m, n_testigos, state)

El siguiente primo fuerte probable es:  107
El siguiente primo fuerte probable es:  227
El siguiente primo fuerte probable es:  347


In [15]:
p = 107*227*347
n_testigos = 200
testigos = np.random.randint(2, p-2, size = n_testigos, dtype = 'int64').tolist()
print("Valor de P: ", p)
testMillerRabinFalsos(p, testigos)

Valor de P:  8428283
No se han obtenido falsos testigos


In [16]:
m = 1000000
n_testigos = 10
state = True
nextPrimo(m, n_testigos, state)
m = 2000000
nextPrimo(m, n_testigos, state)
m = 3000000
nextPrimo(m, n_testigos, state)

El siguiente primo fuerte probable es:  1000667
El siguiente primo fuerte probable es:  2000303
El siguiente primo fuerte probable es:  3000539


In [17]:
p = 1000667*2000303*3000539
n_testigos = 200
testigos = np.random.randint(2, p-2, size = n_testigos, dtype = 'int64').tolist()
print("Valor de P: ", p)
testMillerRabinFalsos(p, testigos)

Valor de P:  6005990488754932439
No se han obtenido falsos testigos


## Ejercicio 08.
#### Repetimos el apartado anterior pero con los números $ n_{1} $ = 3215031751 y $ n_{2} $ = 2199733160881

In [18]:
p = 3215031751
n_testigos = 200
testigos = np.random.randint(2, p-2, size = n_testigos, dtype = 'int64').tolist()
testMillerRabinFalsos(p, testigos)

1286673480, 1586783633, 2489023551, 1033655637, 2040374407, 91457007, 861117149, 222947802, 2586346337, 2033462373, 2921861851, 709991674, 1343100456, 2225067761, 646747271, 1737568457, 3194938597, 14081556, 944703366, 2244019579, 1236458100, 2037289935, 1484557224, 2513810700, 2552782221, 1080714718, 3137055690, 766655560, 1480402395, 340668510, 759410872, 1473715708, 288614357, 1223353920, 1170312199, 1543416776, 2897011296, 2592371990, 1144734878, 2216052231, 2916280521, 2727031433, 144058075, 3049212614, 967638576, 2534443174, 2471525340, 756783323, 1746693732, 531151874, 3102374903, 929942361

En total, se han obtenido  52  falsos testigos de  200


In [19]:
p = 2199733160881
n_testigos = 200
testigos = np.random.randint(2, p-2, size = n_testigos, dtype = 'int64').tolist()
testMillerRabinFalsos(p, testigos)

205526214885, 2108631049409, 1317617320649, 1571330057997, 236286787415, 355662436575, 1422162817436, 45697831188, 1809852635490, 2190129530507, 536728807211, 1349168995834, 49230377747, 1954290055426, 174844278692, 2034738380392, 177780446452, 1354466091635, 766595874338

En total, se han obtenido  19  falsos testigos de  200
